### ISSUE TITLE
gatsby example on using this plugin

### ISSUE THREAD

**Issue by kkannan-carecloud** [kwelch/gatsby-plugin-source-eventbrite#2]
Do you happen to have an eample gatsby app that uses this plugin ?

**Comment by kwelch** [comment]
Yes, I use it for https://codeworking.dev

https://github.com/kwelch/react-codeworking-site/blob/master/gatsby-config.js#L31-L40

**Comment by kwelch** [comment]
The biggest thing to factor in is that it loads the events at build time, so I had to use webhooks to trigger a new build to load new or updated events. 
https://github.com/kwelch/gatsby-plugin-source-eventbrite#keeping-dynamic-content
